version: "3"

services:
  apisix:
    image: apache/apisix:latest
    restart: always
    volumes:
      - ./services/apisix/logs:/usr/local/apisix/logs
      # ro: read only
      - ./services/apisix/config/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./services/apisix/config/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
    # network_mode: host
    ports:
      - "9080:9080/tcp" # HTTP Traffic
      - "9443:9443/tcp" # HTTPs Traffic
      - "9091:9091/tcp" # ~Not~Sure~ prometheus port
      - "9092:9092/tcp" # ~Not~Sure~ control port see: 
    networks:
      apisix:

  quotes:
    build:
      context: ./services/quotes-service/
      dockerfile: Dockerfile
    networks:
      apisix:
  
  jokes:
    build:
      context: ./services/jokes-service/
      dockerfile: Dockerfile
    networks:
      apisix:
  
  random-one:
    build:
      context: ./services/randomizer-service/server-one
      dockerfile: Dockerfile
    networks:
      apisix:
  
  random-two:
    build:
      context: ./services/randomizer-service/server-two
      dockerfile: Dockerfile
    networks:
      apisix:
  
  web-one:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./services/upstream/web-one.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

  web-two:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./services/upstream/web-two.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
