apisix:
  node_listen: 9080 # APISIX Gateway listening port for HTTP Traffic
  enable_ipv6: false
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  admin:
    allow_admin:
      # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.
      - 0.0.0.0/0
    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        # admin: manage all configuration data
        role: admin
      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer
  etcd:
    host:
      # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379"
    prefix: "/apisix" # apisix configurations prefix
    timeout: 30 # 30 seconds

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091